### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by smileklvens** [AleynP/MVVMLin#1]
鄙人看过好多的mvvm，jetpack组件，作者大大应该是借鉴了好多开源框架，整合了其中优秀思想，组装了这个快速开发框架，我也组装了一个，有些地方没并有作者的优雅，这个对我也有了一定的启发，感谢作者，为作者的开源精神点赞，建议加入 常用的扩展及baseactivity页面加入titlebar的控制

**Comment by AleynP** [comment]
感谢支持，会慢慢完善起来，最近在考虑把Flow整合进去，我发现Flow是个好东西

**Comment by smileklvens** [comment]
感谢作者
