### ISSUE TITLE
框架是不错，但是如果我项目中引入的框架也需要集成一个baseactivty那该怎么处理

### ISSUE THREAD

**Issue by qq570026938** [AleynP/MVVMLin#12]

**Comment by AleynP** [comment]
这样的话，你就要自己写一个BaseActivity了，用你自己的BaseActivity继承本库的BaseActivity把第三方的BaseActivity里的方法复制出来，或者用你自己的BaseActivity继承第三方的，把本库的方法复制到你自己写的

**Comment by qq570026938** [comment]
嗯，谢了，还有个问题就是框架有没有实现缓存策略呢，比如先读缓存在更新数据，没网络就读缓存之类的

**Comment by AleynP** [comment]
Demo 里用Room简单实现了缓存，你可以看下Demo首页的数据都有做缓存的，最近也在考虑，把缓存近一步完善一下
