### ISSUE TITLE
Module接入 MVVMLin 的一些注意

### ISSUE THREAD

**Issue by STGing** [AleynP/MVVMLin#16]
因为要对 BaseActivity等内部增加一些东西，所以我选择了以 module 的方式。按照说明，导入后->复制config.gradle文件->增加apply->依赖。 但是依然报错，Plugin with id 'com.novoda.bintray-release' not found  需要把 这行去掉。同时下方的 publish 的任务也去掉。

**Comment by q805699513** [comment]
可以，那个com.novoda.bintray-release只是库包仓库提交用的
