### ISSUE TITLE
网络解析问题

### ISSUE THREAD

**Issue by jackandroid2016** [AleynP/MVVMLin#17]
错误时间返回
![图片](https://user-images.githubusercontent.com/19246186/90010140-f2eb3d80-dcd1-11ea-8595-bdb78514b75d.png)
正确时间返回
![图片](https://user-images.githubusercontent.com/19246186/90010302-3645ac00-dcd2-11ea-824e-9c5e7f27e1cd.png)
data 里边类型不一样，报解析失败，这个能跳过吗，只在成功的时间解析返回data

**Comment by AleynP** [comment]
这个不是框架的问题哦，这是Retrofit的解析问题，原因是你们后台的返回格式不规范，可以跟后台沟通下让他们改，或者你自定义一个适配器
看下这个文章：https://juejin.im/post/6844903975028785159。
不过尽量让后台规范，实在没办法了再自定义适配器，后台的毛病不能惯着

**Comment by jackandroid2016** [comment]
好的，我看下自定义的

**Comment by jackandroid2016** [comment]
![图片](https://user-images.githubusercontent.com/19246186/90113563-2090bf00-dd84-11ea-8d6a-6d151da18aa2.png)
![图片](https://user-images.githubusercontent.com/19246186/90113604-30100800-dd84-11ea-9eeb-5cb5d0e027f3.png)
大神，kotlin这个还在学习过程中，望请解答，这个拦截器确实执行了，并且解析到了错误信息，依然提示解析错误，这个应该是baseviewmodel 里边提示的吧，怎么能过滤掉呢，或者结合起来

**Comment by AleynP** [comment]
BaseViewModel 只是把错误统一处理了，你多看下相关知识，即使你不用BaseViewModel，也会有解析错误
