### ISSUE TITLE
既然用了AndroidUtilCode的话，那么可以直接用 BusUtils，不需要再加入EventBus了

### ISSUE THREAD

**Issue by zhoujia456888** [AleynP/MVVMLin#2]
AndroidUtilCode中的BusUtils介绍
https://github.com/Blankj/AndroidUtilCode/tree/master/plugin/bus-gradle-plugin

**Comment by AleynP** [comment]
嗯嗯，如果用的话会使用BusUtils的，只是考虑要不要加进去这种事件总线的方式
