### ISSUE TITLE
这几天都在学jetpack，mvvm的项目，这是接触的第一个，很新奇，大佬有群不？想加下，多学习一些你的架构想法和思路

### ISSUE THREAD

**Issue by smin9** [AleynP/MVVMLin#3]
这几天都在学jetpack，mvvm的项目，这是接触的第一个，大佬有群不？想加下，多学习一些你的架构想法和思路

**Comment by AleynP** [comment]
还没有群呢，现在刚完成不久，如果以后关注的人多的话会建群的

**Comment by smin9** [comment]
大佬能加下我微信不？以后再拉我进群，15919314445

**Comment by LvanCham** [comment]
建个小小的群？ 交流一下 mvvm  微信或者qq 我拉人

**Comment by AleynP** [comment]
刚弄一个 QQ 群： 473708485
