### ISSUE TITLE
Is the method name called 'TabLayoutAdapter::setImageUrl(TabLayout, List<String>) ' defined incorrectly?

### ISSUE THREAD

**Issue by Coder-Asura** [AleynP/MVVMLin#5]
I think that method name and it's implementation do not match, am I right?

**Comment by AleynP** [comment]
方法名确实命名不规范，那个是设置TabLayout的Item的文本的，当时偷了个懒，复制了ImageAdapter里的方法过来，忘记修改方法名了，不过重要的是@BindingAdapter注解里面的value值和布局里的对应起来就好了，没有影响的，感谢提出后续会更正
